"""empty message

Revision ID: 43cfb53a0c36
Revises: e63970f7458e
Create Date: 2025-05-19 20:18:55.721481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cfb53a0c36'
down_revision = 'e63970f7458e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(length=60), nullable=False),
    sa.Column('diameter', sa.String(length=60), nullable=False),
    sa.Column('gravity', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('orbital_period', sa.String(length=60), nullable=False),
    sa.Column('population', sa.String(length=60), nullable=False),
    sa.Column('rotation_period', sa.String(length=60), nullable=False),
    sa.Column('surface_water', sa.String(length=60), nullable=False),
    sa.Column('terrain', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Planets')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'vehicles', ['vehicle_id'], ['id'])
        batch_op.drop_column('item_type')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('item_type', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('character_id')

    op.create_table('Planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('climate', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('diameter', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('gravity', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('orbital_period', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('population', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('rotation_period', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('surface_water', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('terrain', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Planets_pkey')
    )
    op.drop_table('planets')
    # ### end Alembic commands ###
